"""
Recommendation Generation Module (Phase 4).

Uses Google Gemini API to generate 3 actionable recommendations based on the top themes and quotes.
Enforces anti-hallucination prompts.
"""

import json
import sys
from pathlib import Path
from typing import List

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.append(str(PROJECT_ROOT))
import config
from google import genai
from google.genai import types

def generate_insights(theme_counts: dict, quotes: List[dict]) -> List[str]:
    """
    Generates EXACTLY 3 actionable recommendations based on data using Gemini.
    """
    print("Generating actionable recommendations (via Gemini)...")
    
    if not theme_counts or not quotes:
        return ["Not enough data to generate recommendations."]
        
    is_valid, msg = config.validate_gemini_config()
    if not is_valid:
        print(f"[ERROR] {msg}")
        return ["Configure GEMINI_API_KEY to see AI recommendations."]
        
    client = genai.Client(api_key=config.GEMINI_API_KEY)
    
    # Format context for LLM
    context_str = "Top Themes by Volume:\n"
    for theme, count in theme_counts.items():
        context_str += f"- {theme}: {count} reviews\n"
        
    context_str += "\nRepresentative Quotes:\n"
    for q in quotes:
        context_str += f"- [{q['theme']}] {q['rating']} Stars: {q['quote']}\n"
        
    system_prompt = (
        "You are a Product Manager Assistant analyzing app reviews. "
        "Based on the provided theme volumes and user quotes, generate EXACTLY 3 actionable recommendations for the product team. "
        "CRITICAL RULES:\n"
        "1. ONLY reference information explicitly present in the provided data. Do not hallucinate statistics or features.\n"
        "2. Make recommendations specific and actionable.\n"
        "3. Keep each recommendation under 30 words.\n"
        "4. Return ONLY a JSON object with a single key 'recommendations' containing a list of 3 strings. Do not use Markdown formatting for the JSON."
    )

    try:
        response = client.models.generate_content(
            model=config.GEMINI_MODEL,
            contents=context_str,
            config=types.GenerateContentConfig(
                system_instruction=system_prompt,
                temperature=config.INSIGHT_TEMPERATURE,
                response_mime_type="application/json"
            )
        )
        
        # Parse JSON
        result = json.loads(response.text)
        recs = result.get("recommendations", [])
        
        # Edge case #65: Ensure exactly 3 recommendations
        if not isinstance(recs, list):
            recs = [str(recs)]
            
        while len(recs) < config.REPORT_RECOMMENDATIONS_COUNT:
            recs.append("Monitor user feedback in this area for emerging patterns.")
            
        recs = recs[:config.REPORT_RECOMMENDATIONS_COUNT]
        
        print("[OK] Recommendations generated by Gemini.")
        return recs
        
    except Exception as e:
        print(f"[ERROR] Gemini failed to generate insights: {e}")
        return [
            "Investigate issues mentioned in top themes.",
            "Monitor low-rating reviews for specific pain points.",
            "Follow up on user feedback trends."
        ]

if __name__ == "__main__":
    # Test
    dummy_counts = {"App Performance & UX": 45, "Payments": 20}
    dummy_quotes = [{"theme": "App Performance", "rating": 1, "quote": "App crashes on login"}]
    print(generate_insights(dummy_counts, dummy_quotes))
